[tasks.start-redis]
run = "docker-compose up -d redis"


[tasks.serve]
depends = "start-redis"
run = "uv run main.py"


[tools]
uv = "0.8.17"
pre-commit = "4.3.0"
hadolint = "2.12.0"
python = "3.13.7"
