application:
  applicationName: plugin

  deployment:
    env:
      GITHUB_TOKEN:
        valueFrom:
          secretKeyRef:
            name: github-token
            key: GH_TOKEN

    containerSecurityContext:
      runAsNonRoot: false
      readOnlyRootFilesystem: false

  ingress:
    enabled: true
    ingressClassName: nginx-internal
    annotations:
      kubernetes.io/ingress.class: nginx-internal
    hosts:
      - host: speech-to-text-latest.privatelink.francecentral.azmk8s.io
        paths:
          - path: /
            pathType: Prefix
            servicePort: http

  service:
    ports:
      - name: http
        port: 8080
        targetPort: 8080
