name: app

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      redis:
        condition: service_healthy

    command: python /app/main.py

volumes:
  redis-data:
