name: app

services:
  redis:
    image: redis/redis-stack:latest
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
      - "8001:8001"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
  application:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:

      redis:
        condition: service_healthy

    command: python /app/main.py


volumes:
  redis-data:
