apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-validate-ci-checks-generators-plugin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: argocd-validate-ci-checks-generators-plugin

  # not a good idea to use wildcards but we are in dev mode now and this project won't live long
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - git@github.com:wa101200/argocd-validate-ci-cheks-generators.git
    - https://stakater.github.io/stakater-charts
    - https://redis-stack.github.io/helm-redis-stack/
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-validate-ci-checks-generators-plugin-latest
  namespace: argocd
spec:
  generators:
    - scmProvider:
        github:
          organization: wa101200
          # If true, scan every branch of every repository. If false, scan only the default branch. Defaults to false.
          allBranches: true
          tokenRef:
            secretName: github-token
            key: token
        filters:
          - repositoryMatch: ^argocd-validate-ci-cheks-generators
            branchMatch: configure-k8s

  template:
    metadata:
      name: argocd-validate-ci-checks-generators-plugin-latest
      namespace: argocd
    spec:
      project: argocd-validate-ci-checks-generators-plugin
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
      sources:
        - chart: application
          repoURL: https://stakater.github.io/stakater-charts
          targetRevision: "~6.8"
          helm:
            releaseName: plugin
            valuesObject:
              deployment:
                image:
                  tag: "{{ sha }}"
            valueFiles:
              - $values/manifests/speech-to-text-dev/values/app.values.yaml

        - chart: redis-stack
          repoURL: https://redis-stack.github.io/helm-redis-stack/
          targetRevision: "~0.4.19"
          helm:
            releaseName: redis
            valueFiles:
              - $values/manifests/speech-to-text-dev/values/redis.values.yaml

        - repoURL: git@github.com:wa101200/argocd-validate-ci-cheks-generators
          targetRevision: "{{ sha }}"
          ref: values

        - repoURL: git@github.com:wa101200/argocd-validate-ci-cheks-generators
          targetRevision: "{{ sha }}"
          path: manifests/speech-to-text-dev/resources

      destination:
        server: "https://kubernetes.default.svc"
        namespace: argocd-validate-ci-checks-generators-plugin-latest
