name: lint

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

env:
  PRE_COMMIT_HOME: /home/runner/.cache/pre-commit

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false

      - name: Install mise and tooling
        uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3

      - name: cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ${{ env.PRE_COMMIT_HOME }}
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: run pre-commit
        run: mise exec -- pre-commit run --all-files
