name: test

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  actions: read
  statuses: read
  pull-requests: read
  checks: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  UV_CACHE_DIR: /home/runner/.cache/uv
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.project.directory }}
    strategy:
      fail-fast: false
      matrix:
        project:
          - name: argocd-validate-ci-checks-generator
            directory: app/

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false

      - name: Install mise and tooling
        uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3

      - name: cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: uv-${{ hashFiles(format('{0}/uv.lock', matrix.project.directory)) }}

      - name: uv sync
        run: uv sync --locked

      - name: Run tests
        run: uv run pytest -n 10
